### ISSUE TITLE
Collection of VMR URL and Password

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceLabs/solace-gcp-quickstart#10]
In the instructions, currently there is a mention to replace "<link to VMR image>" within the bash script but they do not mention the "<SolOS/SolAdmin password>" part too. This has the potential to be missed and then break the script execution due to the erroneous angle brackets being left.

For the collection of this information from the reader, I suggest adding variable declarations in the first few lines of the script like so:

```
#!/bin/bash
# Populate the following variables with your entries:
VMR_URL=""
ADMIN_PASSWORD=""

if [ ! -d /var/lib/solace ]; then
...
```

This way the user is not expected to navigate the body of the script and just easily edits the first lines.

Arguments to the second script execution then adapt like so:

`/var/lib/solace/vmr-install.sh -i "${VMR_URL}" -p "${ADMIN_PASSWORD}"
`

**Comment by bczoma** [comment]
This has been implemented in section https://github.com/SolaceProducts/solace-gcp-quickstart#step-2c-add-automated-startup-script
Ready to close.
