### ISSUE TITLE
Enhance instructions in Network Security step

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceLabs/solace-gcp-quickstart#12]
Currently the instructions only highlight the need to open ingress traffic tcp ports. However the newly created instances also need to allow egress traffic to the internet for the setup to work. Can instructions here be enhanced to make this clear and provide screen grabs of an example rule setup. 

Thanks.

**Comment by bczoma** [comment]
Added to the end of section https://github.com/SolaceProducts/solace-gcp-quickstart#step-4-set-up-network-security-to-allow-access
Ready to close.
