### ISSUE TITLE
VMR Deployment failed

### ISSUE THREAD

**Issue by sumeetkoshal** [SolaceLabs/solace-gcp-quickstart#13]
I have uploaded enterprise docker VMR version to my box account and using that URL (it is accessible from anywhere) within startup script.

The VMR failed to download and I had to replace

wget -O /tmp/soltr-docker.tar.gz -nv -a ${LOG_FILE} ${REAL_HTML}

with

wget -O /tmp/soltr-docker.tar.gz -nv -a ${LOG_FILE} ${URL}

in file "vmr-install.sh" to make it work.

**Comment by justinbowes** [comment]
duplicate of #11

**Comment by bczoma** [comment]
The quickstart has been updated, this issue can be closed
