### ISSUE TITLE
Adapt to branding changes

### ISSUE THREAD

**Issue by ChristianHoltfurth** [SolaceLabs/solace-gcp-quickstart#14]
Quickstart will need adapting to new branding... Download URL has changed and Docker image is no longer called solace-app.

**Comment by KenBarr** [comment]
This is an open work item. Will update when scheduled.

**Comment by KenBarr** [comment]
Changes made in commits:

https://github.com/SolaceLabs/solace-gcp-quickstart/commit/13d56b6a69e6d8c638bd60f63cf01b2e69fbe6a6
and
 https://github.com/SolaceLabs/solace-gcp-quickstart/commit/c952d80326096122d74093fe45615e7289911f8c
