### ISSUE TITLE
Guidance on minimal VM Size

### ISSUE THREAD

**Issue by itsJamilAhmed** [SolaceLabs/solace-gcp-quickstart#16]
Is it still correct to say the VM size to be created needs to me mimimal 6 GB memory?
"Select standard 2 vCPU machine type, and at least 6 GB of memory"

Since the 100-connection-tier Docker container can run with 2 GB of memory, does the host need to be given more for it to work?
(https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/Scaling-Tier-Resources.htm)

At the very least, a custom sized VM can be created with exactly 2vCPU and 2GB memory. Will that be sufficient to run the broker?

**Comment by russellsim** [comment]
You are correct. 
README.md is out of date.
We will get README.md updated.

**Comment by PhilippeKhalife** [comment]
Fixed with latest PR.
