### ISSUE TITLE
yum install wget does not always work

### ISSUE THREAD

**Issue by uherbstsolace** [SolaceLabs/solace-gcp-quickstart#19]
Sometimes, 
yum install wget

does not work. Error message:

Jul 25 09:52:57 uli-primary startup-script: INFO startup-script: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
Jul 25 09:52:57 uli-primary startup-script: INFO startup-script: 14: curl#7 - "Failed connect to mirrorlist.centos.org:80; Operation now in progress"
Jul 25 09:52:57 uli-primary startup-script: INFO startup-script: /startup-wc7Dav/tmpOFbc37: line 32: wget: command not found

Obviously, the centos repos or internet access are not available directly after creation of VM.

replace 
yum install -y wget

with:

```
  # Sometimes, the yum repo is not available directly after creating VM
  LOOP_COUNT=0
  while [ $LOOP_COUNT -lt 5 ]; do
    yum install -y wget
    if [ 0 != `echo $?` ]; then 
      ((LOOP_COUNT++))
      sleep 5
    else
      break
    fi
  done
```

**Comment by PhilippeKhalife** [comment]
Fixed with latest PR.
