### ISSUE TITLE
Docker VMR download link error?

### ISSUE THREAD

**Issue by dwmcallister** [SolaceLabs/solace-gcp-quickstart#2]
I'm not sure whether this is correct or not. I think not, but want to check before we simply change and merge.

The "Register Now" button points to https://products.solace.com/download/VMR_DOCKER_COMM, which is a password protected download area.

Should it point at http://dev.solace.com/downloads/download_vmr-ce-docker/ ?

**Comment by KenBarr** [comment]
Fixed as per yourself and Greg over-ruling Osama
