### ISSUE TITLE
Add option to use new cloud init keys

### ISSUE THREAD

**Issue by ChristianHoltfurth** [SolaceLabs/solace-gcp-quickstart#4]
An option to configure the VMR with the new cloud init keys would be great!
http://docs.solace.com/Solace-VMR-Set-Up/Initializing-Config-Keys-With-Cloud-Init.htm?Highlight=cloud%20init

The docker create command could be extended to pass in those environment variables, if set.

**Comment by KenBarr** [comment]
What is the end goal?  General availability of the options, or are you trying to config HA?
If HA, does the AWS type approach work for you? See:
https://github.com/SolaceLabs/solace-aws-ha-quickstart/blob/master/scripts/install-solace.sh

**Comment by ChristianHoltfurth** [comment]
Primarily for HA, but I'd like to be able to pass any of the new v8.4 VMR configuration keys in.
Thanks for pointing out the AWS solution, I wasn't aware that it's already using the new keys!
That would work for HA.

I decided to fork the project [here](https://github.com/ChristianHoltfurth/solace-gcp-quickstart) and detect and pass any of the VMR configuration keys from the environment into the docker container creation. Do you want to close the issue here?

We can either merge the changes back later or keep them as a fork...

**Comment by KenBarr** [comment]
Changes are commited. Closing.
