### ISSUE TITLE
startup script previously installed check

### ISSUE THREAD

**Issue by ChristianHoltfurth** [SolaceLabs/solace-gcp-quickstart#8]
The startup script checks for existence of a file, this should be a directory check instead.
This results in the VMR image being downloaded every time the host is restarted.
Currently:
if [ ! -f /var/lib/solace ]
Change to:
if [ ! -d /var/lib/solace ]

**Comment by bczoma** [comment]
This has been implemented in section https://github.com/SolaceProducts/solace-gcp-quickstart#step-2c-add-automated-startup-script
Ready to close
